module UserPermissionsConstants
  EMPLOYEE_PERMISSION = 'employee'
  INSTRUCTOR_PERMISSION = 'instructor'
  GUEST_PERMISSION = 'guest'
  MANAGER_PERMISSION = 'manager'
  ADMIN_PERMISSION = 'admin'

  ALL_PERMISSIONS = [
    EMPLOYEE_PERMISSION,
    GUEST_PERMISSION,
    MANAGER_PERMISSION,
    ADMIN_PERMISSION,
    INSTRUCTOR_PERMISSION
  ].freeze

  EMPLOYEE_PERMISSIONS = [
    EMPLOYEE_PERMISSION,
    MANAGER_PERMISSION,
    ADMIN_PERMISSION,
    INSTRUCTOR_PERMISSION
  ].freeze

  VIEW_RESERVATION_PERMISSIONS = [
    ADMIN_PERMISSION,
    MANAGER_PERMISSION,
    GUEST_PERMISSION,
    EMPLOYEE_PERMISSION
  ].freeze

  EDIT_RESERVATION_PERMISSIONS = [
    ADMIN_PERMISSION,
    MANAGER_PERMISSION,
    EMPLOYEE_PERMISSION
  ].freeze
end